# Don't use this for production purposes. Docker compose is only for development and staging servers
db:
  image: tutum/mysql:5.5
  env_file:
    - .env
  ports:
    - "5433:3306"
web:
  build: .
  command: bash /code/docker-compose-web-up.sh
  volumes:
    - .:/code
  ports:
    - "3001:3000"
  links:
    - db
  env_file:
    - .env
