# Don't use this for production purposes. Docker compose is only for development and staging servers
db:
  image: mysql
  env_file:
    - .env
  ports:
    - "5433:3306"
web:
  build: .
  # The below is a hackish way to make the web container run indefinitely until stopped
  command: tail -f /dev/null
  volumes:
    - .:/code
  ports:
    - "3001:3000"
  links:
    - db
  env_file:
    - .env
