default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: root
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: example_app_development

test:
  <<: *default
  database: example_app_test

production:
  <<: *default
  database: ENV["MYSQL_DATABASE"]
  username: ENV["MYSQL_USERNAME"]
  password: ENV["MYSQL_PASSWORD"]
  host: ENV["MYSQL_HOST"]
  port: ENV["MYSQL_PORT"]
